### PR TITLE
Limit number fields to uint64

### PR DESCRIPTION
**Pull request by henrypalacios**
Limit number fields to uint64 used on Balance type on polkadot

### CODE REVIEW

**Review by 0xLucca — CHANGES_REQUESTED** [review]
There is something going on with numbers that use the exponential notation. The deploy is not working
image

**Comment by 0xLucca** [comment]
We still have some issues with the type conversion. I will take a look at it

**Comment by 0xLucca** [comment]
We still have some issues with the type conversion. I will take a loot at it
image

**Comment by henrypalacios** [comment]
> We still have some issues with the type conversion. I will take a loot at it image

@0xLucca 
I believe that the objective of the PR has been met, in addition to preventing the case of application lack.

This error you mention above indicates that the input value passed to createType has more bits than the expected 128 bits for the Balance type.

This can be addressed in another PR by looking at what is the maximum decimal precision supported.

**Review by 0xLucca — APPROVED** [review]

**Pull request merged**
